# Setup deck for Travis-CI

language: python
python:
    - "3.6"

notifications:
    email:
        - suave-developers@lists.stanford.edu
  
branches:
    only:
        - master
        - develop
        - jax-develop

before_install:
    - sudo apt-get update
    - sudo apt-get install -qq python3-pip
  
install:
    - cd trunk
    - pip3 install --upgrade pip
    - pip3 install --upgrade numpy
    - pip3 install --upgrade scipy
    - pip3 install --upgrade scikit-learn
    - pip3 install --upgrade matplotlib
    - pip3 install coveralls
    - python3 setup.py develop
    - cd ../regression
  
# run test
script:  
     coverage run automatic_regression.py test
    
after_success:
  coveralls
