version: 2.4.{build}
branches:
  only:
  - master
  - develop
image: Ubuntu2004
build: off

environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN: m09oo3So3XLf7Xx2GzsylzegXi64U9IOG

init:
    - sudo apt-get update
    - sudo apt-get install -qq python3-pip
    
install:
    - cd trunk
    - python3 -m pip install --upgrade pip
    - python3 -m pip install --upgrade numpy
    - python3 -m pip install --upgrade scipy==1.7.3
    - python3 -m pip install --upgrade scikit-learn
    - python3 -m pip install --upgrade matplotlib
    - python3 -m pip install --upgrade plotly
    - PATH=$PATH:/home/appveyor/.local/bin
    - pip install coveralls==3.2.0
    - python3 setup.py develop --user
    - cd ../regression
    
test_script:
  coverage run automatic_regression.py test
     
on_success:
  coveralls